### ISSUE TITLE
Code review from team Heliums 45

### ISSUE THREAD

**Issue by jalasem** [Audrey-Ella-xo/members-only#1]
Hi @euqueme & @Audrey-Ella-xo 👍 well done. 

You're on track. 
However, your sign out button is not working. You might need to move your session methods from the application controller to the session helpers to fix it

**Comment by euqueme** [comment]
> Hi @euqueme & @Audrey-Ella-xo  well done.
> 
> You're on track.
> However, your sign out button is not working. You might need to move your session methods from the application controller to the session helpers to fix it

Thank you Helliums for these awesome suggestions, changes have been made accordingly
